[build]
  command = "npm i"  
          
  node_version = "14"

[build.environment]
  NODE_ENV = "Dev"     

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
